spring:
  application:
    name: bikar-order-deal
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
  datasource:
    username: root
    password: rootpassword
    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
    active: dev
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
cdc-topic:
  name: cdc-offer-deal
dbz:
  transformer:
    table: offer

